### PR TITLE
Part teleport function as substantive func

### PR DESCRIPTION
**Pull request by ghost**
For external use

### CODE REVIEW

**Comment by ghost** [comment]
hmm, for what is this:
`if pos.x>-20 and pos.x<20 and pos.y>-20 and pos.z>-20 and pos.z<20 then`?

**Comment by AndrejIT** [comment]
`if pos.x>-20 and pos.x<20 and pos.y>-20 and pos.z>-20 and pos.z<20 then`
serves two purposes:
1.) to prevent player from using too much server resources by calling /spawn many times per second
2.) it prevents players from easily getting out of "jail" on some servers, including mine.

**Comment by AndrejIT** [comment]
I pushed some of my previous improvements and added you suggested function change on top of that. I hope it is ok...

**Comment by ghost** [comment]
Thanks!

**Comment by AndrejIT** [comment]
Ok, nice!

**Pull request closed without merging**
